# proto-file: com/redpup/justsendit/model/apres/apres.proto
# proto-message: ApresCardList

apres {
  name: "Bar"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Shuffle your deck and reveal 6 [card]. Gain [fun] equal to the total value."
  minor_reward_text: "Shuffle your deck and reveal 3 [card]. Gain [fun] equal to the total value."
}

apres {
  name: "Photo-Op"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Gain 6 [fun] for each [speed] you have."
  minor_reward_text: "Gain 3 [fun] for each [speed] you have."
}

apres {
  name: "Sauna"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Gain 6 [fun] for each unique [training chip] you have."
  minor_reward_text: "Gain 3 [fun] for each unique [training chip] you have."
}

apres {
  name: "Concert"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Gain 1 [fun] for each slope tile without any [fun]."
  minor_reward_text: "Gain 1 [fun] for every 2 slope tiles without any [fun], rounded down."
}

apres {
  name: "Fire Pit"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Gain 4 [fun] for every unique [card] in your discard."
  minor_reward_text: "Gain 2 [fun] for every unique [card] in your discard."
}

apres {
  name: "Dining"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Gain 7 [fun] for every pair of matching [card] in your discard."
  minor_reward_text: "Gain 4 [fun] for every pair of matching [card] in your discard."
}

apres {
  name: "Ice Skating"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Gain 5 [fun] for each [blue] in your discard."
  minor_reward_text: "Gain 3 [fun] for each [blue] in your discard."
}

apres {
  name: "Lodge"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Use the Small reward effects of both other Apres cards in either order."
  minor_reward_text: "Use the Small reward effects either other Apres card."
}

apres {
  name: "Massage"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Take the [fun] here."
  minor_reward_text: "Gain 10 [fun]."
  stockpile_text: "When a player crashes, add 4 [fun] here."
}

apres {
  name: "Karaoke"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Take the [fun] here."
  minor_reward_text: "Gain 10 [fun]."
  stockpile_text: "When a player uses a lift, add 5 [fun] here."
}

apres {
  name: "Fireworks"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Take the [fun] here."
  minor_reward_text: "Gain 10 [fun]."
  stockpile_text: "When a player plays a 9 [card], add 2 [fun] here."
}

apres {
  name: "Dog Sledding"
  available_days: DAY_FRIDAY
  available_days: DAY_SATURDAY
  available_days: DAY_SUNDAY
  major_reward_text: "Take the [fun] here."
  minor_reward_text: "Gain 10 [fun]."
  stockpile_text: "When a player successfully skis or rides on their first turn, add 4 [fun] here."
}
