edition = "2023";

package com.redpup.justsendit.model.supply;

option java_multiple_files = true;
option java_package = "com.redpup.justsendit.model.supply.proto";

import "com/redpup/justsendit/model/supply/icon.proto";
import "com/redpup/justsendit/model/common.proto";
import "com/redpup/matchers/matcher.proto";
import "google/protobuf/empty.proto";

/** A list of skill cards. */
message SkillCardList {
  repeated SkillCard cards = 1;
}

/** A skill card in a player's deck, discard, hand, play, or the shop. */
message SkillCard {
  // Name of the image file of this card.
  string filename = 1;
  // Name of this card.
  string name = 2;
  // Cost of this card.
  uint32 cost = 3;

  // Number of dice on this card, by color.
  uint32 green_dice = 4;
  uint32 blue_dice = 5;
  uint32 black_dice = 6;

  // Icons on this card, if any.
  repeated Icon icons = 7;

  // When this card's effects occur and effects, in order. If none, category
  // is unset.
  EffectCategory category = 8;
  repeated SkillCardEffect effects = 9;

  // Flavor text of this card.
  string flavor_text = 10;

  // Computed attributes of this card.
  message Computed {
    // Expected value of dice.
    double dice_expected_value = 1;
    // Expected value of icons.
    double icon_expected_value = 2;
    // Expected value of effects. If no effects, this is 0.
    double effect_expected_value = 3;
    // Total expected value. Note that this is not necessarily the sum of the
    // above for some effect categories.
    double total_expected_value = 4;
    // Suggested cost based on the total_expected_value and relative to other
    // cards
    uint32 suggested_cost = 5;
  }
  Computed computed = 11;
}

/** One of the effects on a skill card. */
message SkillCardEffect {
  oneof condition {
    google.protobuf.Empty success = 1;
    google.protobuf.Empty discard_card = 2;
  }

  oneof effect {
    AlterDieEffect alter_die = 3;
    GainEffect gain = 4;
    google.protobuf.Empty ignore_wobble = 5;
    CardEffect card_effect = 6;
    google.protobuf.Empty reactivate_following = 7;
    google.protobuf.Empty filter_hand = 8;
    google.protobuf.Empty replenish_shop = 9;
    google.protobuf.Empty extra_turn = 10;
  }
}

/** An effect that alters a die. */
message AlterDieEffect {
  // Matcher for dice that are allowed to be selected for this altering.
  matchers.Matcher die_matcher = 1;

  oneof effect {
    // Rerolls the selected die.
    google.protobuf.Empty reroll = 2;
    // Nudge the selected die by the given value, clamped on valid values.
    uint32 nudge = 3;
  }
}

/** An effect that causes gaining some value. */
message GainEffect {
  oneof gain {
    uint32 skill = 1;
    uint32 points = 2;
    uint32 buys = 3;
    uint32 trashes = 4;
  }

  oneof repeat {
    google.protobuf.Empty skill_card_below = 5;
    google.protobuf.Empty skill_card_above = 6;
    google.protobuf.Empty wobble = 7;
    redpup.matchers.Matcher matching_die = 8;
  }
}

/** An effect that moves skill cards between zones. */
message CardEffect {
  SkillCardZone source_zone = 1;
  SkillCardZone destination_zone = 2;
  uint32 count = 3;
}
