# proto-file: com/redpup/justsendit/model/supply/skill.proto
# proto-message: SkillCardList

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex.png"
  name: "Falling Leaves"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    grade: GRADE_GREEN
  }
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex.png"
  name: "Falling Leaves"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    grade: GRADE_GREEN
  }
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-1.png"
  name: "Pizza Party"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    condition: CONDITION_GROOMED
  }
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-1.png"
  name: "Pizza Party"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    condition: CONDITION_GROOMED
  }
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-2.png"
  name: "Bold Beginnings"
  cost: 1
  green_dice: 2
  blue_dice: 0
  black_dice: 0
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-2.png"
  name: "Bold Beginnings"
  cost: 1
  green_dice: 2
  blue_dice: 0
  black_dice: 0
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-3.png"
  name: "Skill Up"
  cost: 1
  green_dice: 0
  blue_dice: 1
  black_dice: 0
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-3.png"
  name: "Skill Up"
  cost: 1
  green_dice: 0
  blue_dice: 1
  black_dice: 0
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-4.png"
  name: "Signature Style"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    wild: true
  }
  text: "use [Fri] effect"
}

cards {
  filename: "src/main/resources/com/redpup/justsendit/img/skill_cards/Skill Card Front Complex-5.png"
  name: "Just Send It"
  cost: 1
  green_dice: 3
  blue_dice: 0
  black_dice: 0
}

