# proto-file: com/redpup/justsendit/model/board/tile/tile.proto
# proto-message: MountainTileList

tiles {
  slope {
    difficulty: 2
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile.png"
}

tiles {
  slope {
    difficulty: 3
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-1.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-2.png"
}

tiles {
  slope {
    difficulty: 2
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-3.png"
}

tiles {
  slope {
    difficulty: 3
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-4.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-5.png"
}

tiles {
  slope {
    difficulty: 2
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-6.png"
}

tiles {
  slope {
    difficulty: 3
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-7.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-8.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-9.png"
}

tiles {
  slope {
    difficulty: 2
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-10.png"
}

tiles {
  slope {
    difficulty: 3
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-11.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-12.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-13.png"
}

tiles {
  slope {
    difficulty: 3
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-14.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-15.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-16.png"
}

tiles {
  slope {
    difficulty: 6
    grade: GRADE_GREEN
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-17.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-18.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-19.png"
}

tiles {
  slope {
    difficulty: 6
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: true
  }
  filename: "Tile-20.png"
}

tiles {
  slope {
    difficulty: 4
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-21.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-22.png"
}

tiles {
  slope {
    difficulty: 6
    grade: GRADE_GREEN
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-23.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-24.png"
}

tiles {
  slope {
    difficulty: 6
    grade: GRADE_GREEN
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-25.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_POWDER
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-26.png"
}

tiles {
  slope {
    difficulty: 6
    grade: GRADE_GREEN
    condition: CONDITION_POWDER
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-27.png"
}

tiles {
  slope {
    difficulty: 5
    grade: GRADE_GREEN
    condition: CONDITION_ICE
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-28.png"
}

tiles {
  slope {
    difficulty: 6
    grade: GRADE_GREEN
    condition: CONDITION_ICE
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-29.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-30.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-31.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-32.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-33.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-34.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-35.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-36.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-37.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-38.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-39.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-40.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-41.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-42.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-43.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-44.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-45.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-46.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-47.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-48.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-49.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-50.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-51.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-52.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-53.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-54.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-55.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-56.png"
}

tiles {
  slope {
    difficulty: 7
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-57.png"
}

tiles {
  slope {
    difficulty: 8
    grade: GRADE_BLUE
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-58.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLUE
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-59.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-60.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-61.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-62.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-63.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_GROOMED
    slow: false
  }
  filename: "Tile-64.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-65.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-66.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-67.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-68.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-69.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-70.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-71.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-72.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-73.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-74.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-75.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-76.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-77.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-78.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-79.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-80.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-81.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-82.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-83.png"
}

tiles {
  slope {
    difficulty: 9
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-84.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-85.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-86.png"
}

tiles {
  slope {
    difficulty: 12
    grade: GRADE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_CLIFFS
    slow: false
  }
  filename: "Tile-87.png"
}

tiles {
  slope {
    difficulty: 10
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-88.png"
}

tiles {
  slope {
    difficulty: 11
    grade: GRADE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_CLIFFS
    slow: false
  }
  filename: "Tile-89.png"
}

tiles {
  slope {
    difficulty: 13
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_ICE
    slow: false
  }
  filename: "Tile-90.png"
}

tiles {
  slope {
    difficulty: 14
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_POWDER
    slow: false
  }
  filename: "Tile-91.png"
}

tiles {
  slope {
    difficulty: 15
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-92.png"
}

tiles {
  slope {
    difficulty: 13
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-93.png"
}

tiles {
  slope {
    difficulty: 14
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    slow: false
  }
  filename: "Tile-94.png"
}

tiles {
  slope {
    difficulty: 15
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-95.png"
}

tiles {
  slope {
    difficulty: 13
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_MOGULS
    hazards: HAZARD_TREES
    slow: false
  }
  filename: "Tile-96.png"
}

tiles {
  slope {
    difficulty: 14
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_CLIFFS
    slow: false
  }
  filename: "Tile-97.png"
}

tiles {
  slope {
    difficulty: 15
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_ICE
    hazards: HAZARD_CLIFFS
    slow: false
  }
  filename: "Tile-98.png"
}

tiles {
  slope {
    difficulty: 16
    grade: GRADE_DOUBLE_BLACK
    condition: CONDITION_POWDER
    hazards: HAZARD_CLIFFS
    slow: false
  }
  filename: "Tile-99.png"
}

tiles {
  lift {
    color: LIFT_COLOR_RED
    direction: LIFT_DIRECTION_TOP
  }
  filename: "Tile-100.png"
}

tiles {
  lift {
    color: LIFT_COLOR_RED
    direction: LIFT_DIRECTION_BOTTOM
    min_cards: 1
    max_cards: 1
  }
  filename: "Tile-101.png"
}

tiles {
  lift {
    color: LIFT_COLOR_CYAN
    direction: LIFT_DIRECTION_TOP
  }
  filename: "Tile-102.png"
}

tiles {
  lift {
    color: LIFT_COLOR_CYAN
    direction: LIFT_DIRECTION_BOTTOM
    min_cards: 1
    max_cards: 1
  }
  filename: "Tile-103.png"
}

tiles {
  lift {
    color: LIFT_COLOR_YELLOW
    direction: LIFT_DIRECTION_TOP
  }
  filename: "Tile-104.png"
}

tiles {
  lift {
    color: LIFT_COLOR_YELLOW
    direction: LIFT_DIRECTION_BOTTOM
    min_cards: 2
    max_cards: 2
  }
  filename: "Tile-105.png"
}

tiles {
  lift {
    color: LIFT_COLOR_PINK
    direction: LIFT_DIRECTION_TOP
  }
  filename: "Tile-106.png"
}

tiles {
  lift {
    color: LIFT_COLOR_PINK
    direction: LIFT_DIRECTION_BOTTOM
    min_cards: 2
    max_cards: 2
  }
  filename: "Tile-107.png"
}

tiles {
  lift {
    color: LIFT_COLOR_GREY
    direction: LIFT_DIRECTION_TOP
  }
  filename: "Tile-108.png"
}

tiles {
  lift {
    color: LIFT_COLOR_GREY
    direction: LIFT_DIRECTION_BOTTOM
    min_cards: 1
    max_cards: 2
  }
  filename: "Tile-109.png"
}

