package com.redpup.justsendit

import com.redpup.justsendit.proto.Test
import com.redpup.justsendit.proto.test
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test as JUnitTest

class ProtobufTest {

  @JUnitTest
  fun `test Java and Kotlin interop for Test message`() {
    val expectedValue = 42

    // 1. Using the classic Java Builder (generated by protobuf-java)
    val javaMessage = Test.newBuilder()
      .setValue(expectedValue)
      .build()

    // 2. Using the new Kotlin DSL (generated by protobuf-kotlin)
    // Note: 'test' is the DSL factory function generated for the 'Test' message
    val kotlinMessage = test {
      value = expectedValue
    }

    // Verify both produce the same underlying data
    assertEquals(expectedValue, javaMessage.value)
    assertEquals(javaMessage, kotlinMessage)

    println("Protobuf Java Value: ${javaMessage.value}")
    println("Protobuf Kotlin Value: ${kotlinMessage.value}")
  }
}