# proto-file: com/redpup/justsendit/model/supply/skill.proto
# proto-message: SkillCardList

cards {
  name: "Pizza Party"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    grade: GRADE_GREEN
  }
  flavor_text: "Slow and wide, easy-cheesy"
}

cards {
  name: "Pizza Party"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    grade: GRADE_GREEN
  }
  flavor_text: "Slow and wide, easy-cheesy"
}

cards {
  name: "Falling Leaf"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    condition: CONDITION_GROOMED
  }
  flavor_text: "Heel side, so you can enjoy the view"
}

cards {
  name: "Falling Leaf"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    condition: CONDITION_GROOMED
  }
  flavor_text: "Heel side, so you can enjoy the view"
}

cards {
  name: "Wild Ride"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  icons {
    wild: true
  }
  flavor_text: "You'll never believe how far you'll go"
}

cards {
  name: "Just Send It"
  cost: 1
  green_dice: 3
  blue_dice: 0
  black_dice: 0
  flavor_text: "If you don't know..."
}

cards {
  name: "Bold Beginnings"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  category: EFFECT_CATEGORY_PLAY
  effects {
    alter_die {
      die_matcher {
        enum_matcher {
          enum_type_name: "com.redpup.justsendit.model.Die"
          name_matcher {
            string_matcher { value: "DIE_GREEN" }
          }
        }
      }
      reroll {}
    }
  }
  flavor_text: "Lean forward and let the adventure begin"
}

cards {
  name: "Still Standing"
  cost: 1
  green_dice: 1
  blue_dice: 0
  black_dice: 0
  category: EFFECT_CATEGORY_PLAY
  effects {
    alter_die {
      die_matcher {
        enum_matcher {
          enum_type_name: "com.redpup.justsendit.model.Die"
          name_matcher {
            string_matcher { value: "DIE_GREEN" }
          }
        }
      }
      nudge: 1
    }
  }
  flavor_text: "Standing still never felt so good"
}

cards {
  name: "Skill Up"
  cost: 1
  green_dice: 0
  blue_dice: 1
  black_dice: 0
  flavor_text: "Every run teaches you something new"
}

cards {
  name: "Stroke of Genius"
  cost: 1
  green_dice: 0
  blue_dice: 0
  black_dice: 1
  flavor_text: "Practice, meet perfect"
}

