# proto-file: com/redpup/justsendit/model/supply/skill_card.proto
# proto-message: SkillCardList

cards {
  name: "Green Starter"
  cost: 0
  green_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Green Starter"
  cost: 0
  green_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Green Starter"
  cost: 0
  green_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Green Starter"
  cost: 0
  green_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Green Starter"
  cost: 0
  green_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}

cards {
  name: "Blue Starter"
  cost: 0
  blue_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Blue Starter"
  cost: 0
  blue_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Blue Starter"
  cost: 0
  blue_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}

cards {
  name: "Black Starter"
  cost: 0
  black_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
cards {
  name: "Black Starter"
  cost: 0
  black_dice: 1
  category: EFFECT_CATEGORY_PLAY
  text: "No effect."
}
