# proto-file: com/redpup/justsendit/model/player/player.proto
# proto-message: PlayerCardList

player {
  name: "George"
  day: DAY_FRIDAY
  skill_cards: GRADE_GREEN
  skill_cards: GRADE_GREEN
  skill_cards: GRADE_GREEN
  skill_cards: GRADE_GREEN
  skill_cards: GRADE_BLUE
  skill_cards: GRADE_BLUE
  skill_cards: GRADE_BLUE
  skill_cards: GRADE_BLUE
  skill_cards: GRADE_BLACK
  skill_cards: GRADE_BLACK
  ability_name: "First Chair or Bust"
  ability_text: "Gain 1 [Fun] when you ski a fresh slope."
}
